### ISSUE TITLE
metadata and tweets

### ISSUE THREAD

**Issue by sdaza** [alexlitel/congresstweets#2]
Hello, 
I am interested in analyzing only Congress members tweets. I realized that not all the info in the metadata file (users-filtered.json) matches the tweeter data. 

Do you suggest a reliable way to match Congress metadata info (e.g., party affiliation) to the tweets data? Screen names are not always the same in both data sources. 

Thanks!

**Comment by alexlitel** [comment]
The users-filtered.json file has to be continually updated because of additions or departures from Congress, so there's a decent likelihood it will not be 1:1 with old data. 

But I could ameliorate some issues from the automator side by (1) adding the user's id_str to the Tweet class instantiation (a user's screen name, as you note, are subject to change) and (2) figuring out some manner of archiving the old users.json & users-filtered.json datasets. I was planning to deposit the tweet data to the Internet Archive in the future to deal with the repo space finiteness issue, so could do that with the user datasets as well, but adding all-encompassing historical dataset is probably easier.

Once I do that, retroactively adding user id_str to old datasets in this repo shouldn't be too much work.

**Comment by sdaza** [comment]
That would be great!

**Comment by alexlitel** [comment]
Addressed with latest commit.

**Comment by sdaza** [comment]
Do metadata have the user id? That would be `id`?

**Comment by alexlitel** [comment]
@sdaza Yes, that would be the `id` field in objects in the accounts array.

**Comment by sdaza** [comment]
Thanks @alexlitel !
