### ISSUE TITLE
Problem with Page 2

### ISSUE THREAD

**Issue by sdaza** [alexlitel/congresstweets#4]
Page 2 gives an error: 

https://alexlitel.github.io/congresstweets/
https://alexlitel.github.io/page2

**Comment by alexlitel** [comment]
That's actually by design. The archive in the repo is only supposed to be limited to the past 100 days with the rest available via the Internet Archive. I actually need to hardcode the start date to the backend/Redis store and prevent pagination on the frontend.

Old datasets will be archived here: [https://archive.org/details/tweetsofcongress](https://archive.org/details/tweetsofcongress
)

**Comment by sdaza** [comment]
Great, thank you!
