### ISSUE TITLE
why remove 2017 data?

### ISSUE THREAD

**Issue by AlJohri** [alexlitel/congresstweets#6]
hi @alexlitel, I was wondering why you removed 2017 data in this commit? https://github.com/alexlitel/congresstweets/commit/4b11913723b9811c155c7b732084fe3bab9c5ad0

also, have you considered mirroring to a public s3 bucket if there are any concerns with data size? the cost should be minimal

**Comment by alexlitel** [comment]
Hey @AlJohri, the files were removed as a quick fix because the Github API was rejecting the commits from the automator/backend due to the amount of data in the repo.

The project was never intended to house more than a year's worth of datasets.  Ostensibly, this repo should only house the last 100 days of datasets, but removing individual files from Git trees using the API doesn't seem to work as it should in theory (or as it did in much smaller test repos). I haven't had a chance to fix the Github process on the backend yet to address/simplify things. And I think it might be possible that changing the process could prevent the data size issue from occurring for a longer period of time. 

The 2017 datasets are mirrored in the Archive.org collection at https://archive.org/details/tweetsofcongress, which is also linked in this repo's README. It's imperfect (some datasets uploaded last year and missing retroactive tweet additions) and a little more setup than just downloading this repo with everything in a single directory, but I think it's a little more philosophically compatible for an open data project than an S3 bucket on AWS. There's a predictable URL structure to the ZIP files in the Archive collection in the archive, so you can just iterate through them to download.

Let me know if there are any other questions.

**Comment by AlJohri** [comment]
Thanks @alexlitel. I think the archive.org data will work for us- I missed to see that in the README.

P.S. I didn't realize you could store data on archive.org; that sounds like a great resource for future open data projects. Can you revise those archives at a later date if needed?
