### ISSUE TITLE
ID for retweets

### ISSUE THREAD

**Issue by jflanaga** [alexlitel/congresstweets#7]
HI, 
Nice resource. I'm a bit puzzled about what the `id` is supposed to represent in the dataset. In many cases (I think it's in the case for retweets), the `id` doesn't match the number in the link. That sorta makes sense, since the link is the link for the original tweet, not the retweet. And I thought that was a bit odd, since I thought the link would go the legislator's timeline, not the timeline for the person who tweeted it.

The reason I ask is that I'm trying to hydrate the entire tweets for the tweets ID in your dataset. I just tried a bunch, and I only got about half (30,000 out of 60,000). People do delete tweets, so they wouldn't get collected during the hydration process, but that's a much higher percentage of missing tweets than I've ever seen before. I'm not entirely sure yet which ones are missing: I started looking at the IDs and the links and got confused as to how the dataset was put together.

**Comment by alexlitel** [comment]
The id is the `id_str` (id string) from the Twitter API which is a unique identifier for every tweet and appears in Twitter URLs  as `twitter.com/<username>/statuses/<id_str>`. 

When someone retweets a tweet on Twitter, it is given a unique ID, and it is a new tweet entity according to the API (with the info of the original tweet embedded inside), but if you were to go to to `twitter.com/<username>/statuses/<id_str>` in a browser,  it would ultimately resolve/redirect to the original URL. Retweeted URLs do not actually ever resolve to the retweeter/legislator's feed.

Since it redirects to the original URL and the retweet URL will no longer redirect if the retweet is deleted, I chose to use the original tweet's URL because that might be the best chance of getting a functioning URL. No matter what username you put in the URL, if it is a valid tweet id string that hasn't been deleted, it will actually redirect to the original tweet URL. If you're using a scraper, make sure you are enabling redirects. If you are using the API, make sure you use the tweet `id_str`.

Aside from deleted tweets, URLs can be inaccurate because accounts are deleted (legislators are unfortunately not required to archive/preserve) and accounts get suspended. 

Also, the 30,000 deleted tweet count sounds actually really low to me—it would be somewhere around 27 tweets / dataset. Are you using some kind of subset?

And textually, I would say the tweet text in datasets are fairly complete. They include full URLs, full data of quoted tweets, full data of retweets with quoted tweets, and resolved shortened URLs, which most datasets do not.

**Comment by jflanaga** [comment]
Thanks. I’m pretty familiar with the Twitter API, so I just wanted to make sure the ID in your set was taken from the API and didn’t represent something else. I’m not subsetting at all, I’m just creating a text file of the tweet IDs from your dataset and then using `twarc` to hydrate them. The text file has 60000 ids, but the returned json only had 31000, so something is off. The tweets are from earlier this year, and I wouldn’t have expected that many to have been deleted. I’ll just investiage on my own.

The text field is pretty complete in your dataset but so I can use regular expressions to get what I want for network analysis

**Comment by jflanaga** [comment]
Sorry, I'll just add another comment to illustrate the issue. I'm looking at `2020-01-16.json` file. There's 3198 listed, but if you harvest the tweet ids, there's only 1498. I looked at two that were missing to see what the issue was. The second tweet in your the json is from `Norma4Congress`  with an id of `1217683334370856960`. I then harvested the tweets from the user and found the tweet that was missing. It has an id `1217683334370856961` (so the last digit is different by 1). I thought maybe it was deleted and the retweeted again. However the timestamps appear to be the same: 

```
Thu Jan 16 05:41:45 +0000 2020  (from Twitter API
2020-01-16T00:41:45-05:00
```
Then I saw the next one that was missing. This has a tweet ID of `1217675066932113408`. Then I scraped that legislator's timeline and retrieved the missing tweet. It has a tweet id of `
1217675066932113410` (now the final digit is off by 2). Again, I checked the date, and they look the same: 

```
Thu Jan 16 05:08:53 +0000 2020
2020-01-16T00:08:53-05:00

```
The next one is only off by one again, so it's not being incremented. 

As I said, I'm not sure what's going on. Maybe they are being deleted and retweeted almost instantly, but I just wanted to let you know about it, in case there is some kind of bug somewhere. Not sure what that would be, however, as extracting the ID from the Twitter API is pretty straightforward, and I don't know any reason why the final digit would be off by one or two unless the user is deleting one and the posting it again. As far as I can tell, the direction of the difference (the tweet IDs here are prior to the ones I get from the timeline) would suggest it.

**Comment by alexlitel** [comment]
What language are you using? I think you might be inadvertently are coercing the ids from a string to integer, or have some other error (race condition?).

The `Norma4Congress` tweet in the dataset has an id of `1217683334370856961` (not `1217683334370856960`) and https://twitter.com/Norma4Congress/status/1217683334370856961 is a functioning extant link.

The next tweet has an id of `1217676206331650048` (not `1217675066932113408`) and it's again an extant URL. The `1217675066932113410` tweet is a completely different tweet but also still appears in the dataset.

You might also be extracting `id`s rather than `id_str` from the API, which not all languages can interpret correctly.

**Comment by jflanaga** [comment]
thanks for that. I should have checked the original json file rather than what was imported. I just used Pandas instead of doing it myself out of laziness. Somewhere I must have made a mistake.  Sorry for taking up your time
